### PR TITLE
fixes homebrew deprecation warning

### LINKED ISSUE #2: Warning: Calling 'depends_on :python' is deprecated!
saw this on `brew update` today:

```
Warning: Calling 'depends_on :python' is deprecated!
Use 'depends_on "python"' instead.
/usr/local/Homebrew/Library/Taps/dflemstr/homebrew-tools/v8.rb:21:in `<class:V8>'
Please report this to the dflemstr/tools tap!
```

### PR DESCRIPTION
**Pull request by sodiumjoe**
fixes #2

### CODE REVIEW

**Comment by sodiumjoe** [comment]
I don't really know how to test whether this works.

File: v8.rb [hunk 1]
```diff
@@ -18,7 +18,7 @@ class V8 < Formula
   # https://github.com/Homebrew/homebrew/issues/21426
   depends_on :macos => :lion
 
-  depends_on :python => :build
+  depends_on python => :build
```
Comment (bencomp) [inline v8.rb]: I came here because I saw the same warning – thanks for your efforts!

The warning includes double quotes around `python` to make the whole line `depends_on "python" => :build` (similar to lines below).

**Comment by bencomp** [comment]
Even though the change doesn't include double quotes, it looks like the Travis build failed because of a connection issue between Travis and GitHub.

File: v8.rb (hunk 1 above)
Comment (sodiumjoe) [reply v8.rb]: thanks, fixed!

**Comment by sodiumjoe** [comment]
yeah, not sure what to do about that besides ping @dflemstr

**Comment by dflemstr** [comment]
This repo is on very low maintenance status for me (I have never even owned a mac!), so thanks for figuring this one out!
